#!/bin/bash

echo "🔧 WEBHOOK CONFIGURATION OPTIONS"
echo "================================"
echo ""
echo "You have 2 options to fix the webhook:"
echo ""
echo "OPTION 1: Use Direct VM URL (Recommended - Permanent)"
echo "------------------------------------------------------"
echo "Update Meta Business Manager with:"
echo "Webhook URL: http://159.89.166.94:3000/webhook"
echo "Verify Token: jarvish_webhook_2024"
echo ""
echo "✅ Pros: Permanent, no ngrok needed, always same URL"
echo "❌ Cons: Uses HTTP (not HTTPS)"
echo ""
echo "OPTION 2: Fix Ngrok (Temporary)"
echo "--------------------------------"
echo "1. Get ngrok authtoken from: https://dashboard.ngrok.com/"
echo "2. SSH to VM: ssh root@159.89.166.94"
echo "3. Run: ngrok config add-authtoken YOUR_TOKEN"
echo "4. Run: ngrok http 3000"
echo "5. Update Meta with new ngrok URL"
echo ""
echo "✅ Pros: HTTPS, familiar setup"
echo "❌ Cons: URL changes on restart, needs authtoken"
echo ""
echo "📌 QUICKEST FIX:"
echo "Just update Meta with: http://159.89.166.94:3000/webhook"
