#!/bin/bash

echo "🔴 FIXING META WEBHOOK VALIDATION ERROR"
echo "========================================"
echo ""
echo "Common issues and fixes:"
echo ""

echo "1️⃣ CHECK IF WEBHOOK IS ACTUALLY RUNNING:"
echo "ssh root@YOUR_VM_IP"
echo "pm2 status"
echo ""
echo "If not running:"
echo "cd /home/mvp/webhook"
echo "pm2 start webhook.js --name finadvise-webhook"
echo ""

echo "2️⃣ CHECK IF PORT 3000 IS OPEN:"
echo "# On your VM:"
echo "sudo ufw status"
echo ""
echo "If port 3000 not listed:"
echo "sudo ufw allow 3000"
echo "sudo ufw reload"
echo ""

echo "3️⃣ TEST WEBHOOK LOCALLY ON VM:"
echo "curl http://localhost:3000/webhook?hub.mode=subscribe&hub.verify_token=jarvish_webhook_2024&hub.challenge=test123"
echo ""
echo "Should return: test123"
echo ""

echo "4️⃣ TEST FROM YOUR COMPUTER:"
echo "curl \"http://YOUR_VM_IP:3000/webhook?hub.mode=subscribe&hub.verify_token=jarvish_webhook_2024&hub.challenge=test123\""
echo ""

echo "5️⃣ CHECK DIGITAL OCEAN FIREWALL:"
echo "- Go to Digital Ocean dashboard"
echo "- Click on your droplet"
echo "- Go to Networking → Firewalls"
echo "- Make sure port 3000 is allowed for inbound traffic"
echo ""

echo "6️⃣ USE ALTERNATIVE PORT 80 (NO PORT IN URL):"
echo "# On VM, stop current webhook:"
echo "pm2 stop finadvise-webhook"
echo ""
echo "# Edit webhook to use port 80:"
echo "nano /home/mvp/webhook/webhook.js"
echo "# Change port: 3000 to port: 80"
echo ""
echo "# Start on port 80:"
echo "sudo pm2 start webhook.js --name finadvise-webhook"
echo ""
echo "# Then use URL without port:"
echo "http://YOUR_VM_IP/webhook"
echo ""

echo "7️⃣ QUICK FIX WITH NGROK (TEMPORARY):"
echo "# Install ngrok on VM:"
echo "curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null"
echo "echo \"deb https://ngrok-agent.s3.amazonaws.com buster main\" | sudo tee /etc/apt/sources.list.d/ngrok.list"
echo "sudo apt update && sudo apt install ngrok"
echo ""
echo "# Run ngrok:"
echo "ngrok http 3000"
echo ""
echo "# Use the HTTPS URL from ngrok in Meta"