#!/bin/bash

echo "🔥 FREE HTTPS SOLUTION USING CLOUDFLARE"
echo "========================================"
echo ""
echo "This gives you a FREE domain + SSL certificate!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Get a FREE subdomain from FreeDNS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://freedns.afraid.org"
echo "2. Sign up for free account"
echo "3. Create subdomain like: finadvise.mooo.com"
echo "4. Point it to your VM IP"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Add to Cloudflare (FREE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up at cloudflare.com (FREE)"
echo "2. Add your domain"
echo "3. Use Cloudflare's free SSL"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "EASIER SOLUTION: Use webhook.site"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "For testing only:"
echo "1. Go to https://webhook.site"
echo "2. Get your unique URL"
echo "3. Use that HTTPS URL in Meta"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SIMPLEST: Use Port 80 (HTTP might work)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run on your VM:"
echo ""
echo "cd /home/mvp/webhook"
echo "pm2 stop all"
echo "sudo pm2 start webhook-port-80.js --name webhook"
echo ""
echo "Then try in Meta:"
echo "http://YOUR_VM_IP/webhook"