#!/bin/bash

echo "📌 TO GET NGROK WORKING, YOU NEED YOUR AUTHTOKEN"
echo "================================================"
echo ""
echo "STEP 1: Get your ngrok authtoken"
echo "---------------------------------"
echo "1. Go to: https://dashboard.ngrok.com/signup (or login)"
echo "2. Get your authtoken from: https://dashboard.ngrok.com/get-started/your-authtoken"
echo "3. Copy the authtoken (looks like: 2nWVCXp...)"
echo ""
echo "STEP 2: Set it up on VM"
echo "------------------------"
echo "Run this command with YOUR token:"
echo ""
echo "SSHPASS='droplet' sshpass -e ssh root@159.89.166.94 << 'SETUP'"
echo "ngrok config add-authtoken YOUR_AUTHTOKEN_HERE"
echo "pkill -f ngrok"
echo "nohup ngrok http 3000 > /tmp/ngrok.log 2>&1 &"
echo "sleep 5"
echo "curl -s http://localhost:4040/api/tunnels | python3 -m json.tool"
echo "SETUP"
echo ""
echo "STEP 3: Get your HTTPS URL"
echo "---------------------------"
echo "After running above, you'll see your new ngrok URL"
echo "Update it in Meta Business Manager"
echo ""
echo "================================================"
echo "OR PROVIDE ME YOUR AUTHTOKEN AND I'LL DO IT FOR YOU!"
