#!/bin/bash

echo "🔥 IMMEDIATE FIX FOR META WEBHOOK VALIDATION"
echo "==========================================="
echo ""
echo "RUN THESE COMMANDS ON YOUR VM RIGHT NOW:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 1: Quick Fix with Ngrok (5 minutes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Step 1: SSH into your VM"
echo "ssh root@YOUR_VM_IP"
echo ""
echo "# Step 2: Install ngrok quickly"
echo "wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
echo "tar xvzf ngrok-v3-stable-linux-amd64.tgz"
echo "sudo mv ngrok /usr/local/bin"
echo ""
echo "# Step 3: Make sure your webhook is running"
echo "cd /home/mvp/webhook"
echo "pm2 stop all"
echo "pm2 start webhook-for-vm.js --name webhook"
echo ""
echo "# Step 4: Start ngrok"
echo "ngrok http 3000"
echo ""
echo "# You'll see something like:"
echo "# Forwarding: https://abc123.ngrok-free.app -> http://localhost:3000"
echo ""
echo "# Step 5: Use this in Meta:"
echo "Callback URL: https://YOUR_NGROK_URL.ngrok-free.app/webhook"
echo "Verify Token: jarvish_webhook_2024"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 2: Direct IP (if Meta accepts HTTP)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Step 1: Get your VM IP"
echo "curl ifconfig.me"
echo ""
echo "# Step 2: Ensure port 3000 is open"
echo "sudo ufw allow 3000"
echo "sudo ufw reload"
echo ""
echo "# Step 3: Start webhook on port 3000"
echo "cd /home/mvp/webhook"
echo "pm2 stop all"
echo "pm2 start webhook-for-vm.js --name webhook"
echo ""
echo "# Step 4: Test it's working"
echo "curl http://localhost:3000/health"
echo ""
echo "# Step 5: In Meta, use:"
echo "Callback URL: http://YOUR_VM_IP:3000/webhook"
echo "Verify Token: jarvish_webhook_2024"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTION 3: Port 80 (no port in URL)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Step 1: Copy webhook-port-80.js to VM"
echo "scp webhook-port-80.js root@YOUR_VM_IP:/home/mvp/webhook/"
echo ""
echo "# Step 2: On VM, start on port 80"
echo "cd /home/mvp/webhook"
echo "pm2 stop all"
echo "sudo pm2 start webhook-port-80.js --name webhook"
echo ""
echo "# Step 3: In Meta, use:"
echo "Callback URL: http://YOUR_VM_IP/webhook"
echo "Verify Token: jarvish_webhook_2024"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚨 MOST LIKELY TO WORK: NGROK (OPTION 1)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Meta often requires HTTPS. Ngrok provides this instantly."
echo "The URL will look like: https://abc123.ngrok-free.app/webhook"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 YOUR WEBHOOK DETAILS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Phone Number ID: 574744175733556"
echo "Access Token: EAATOFQtMe9gBPXrmwK1MDrvlBAWfbeevjzXs8PgT15GPsKADHmzJPWZBvnyhAYTjSfoAzOZC97CHQ27X6jE1iOjNZCehO2WrxPiEfRnhLO3sZA0iJ93Sh7ZB49ZBnF12CWCVTpB1WMfpRgpCdv5hXWIbWgzaHFovUPaZBQBDSa7p74ZCIKvZCtyLo3rj8dzDZAs74GaQZDZD"
echo "Verify Token: jarvish_webhook_2024"
echo ""
echo "Test after setup:"
echo "Send 'Hello' to your WhatsApp number"
echo "Watch logs: pm2 logs webhook"