#!/bin/bash

echo "🔍 GETTING YOUR WEBHOOK URL"
echo "============================"
echo ""
echo "Run this on your Digital Ocean VM:"
echo ""
echo "# Get your public IP:"
echo "curl ifconfig.me"
echo ""
echo "Your IP will be something like: 134.209.154.123"
echo ""
echo "Then your webhook details are:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📍 WEBHOOK URL:"
echo "http://YOUR_IP:3000/webhook"
echo ""
echo "🔑 VERIFY TOKEN:"
echo "jarvish_webhook_2024"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Example:"
echo "If your IP is 134.209.154.123, then use:"
echo "http://134.209.154.123:3000/webhook"